apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: kafka
message: KAFKA
metadata:
  annotations:
    description: KAFKA
    tags: quickstart,KAFKA
  name: kafka
  namespace: openshift
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: kafka1
    name: kafka1-service
    namespace: default
  spec:
    clusterIP: None
    ports:
    - port: 9092
      protocol: TCP
      targetPort: 9092
      name: kafka
    - port: 1099
      protocol: TCP
      targetPort: 1099
      name: jmx
    selector:
      app: kafka1
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: kafka2
    name: kafka2-service
    namespace: default
  spec:
    clusterIP: None
    ports:
    - port: 9092
      protocol: TCP
      targetPort: 9092
      name: kafka
    - port: 1099
      protocol: TCP
      targetPort: 1099
      name: jmx
    selector:
      app: kafka2
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: kafka3
    name: kafka3-service
    namespace: default
  spec:
    clusterIP: None
    ports:
    - port: 9092
      protocol: TCP
      targetPort: 9092
      name: kafka
    - port: 1099
      protocol: TCP
      targetPort: 1099
      name: jmx
    selector:
      app: kafka3
    sessionAffinity: None
    type: ClusterIP
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: kafka1-deployment
    namespace: default
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: kafka1
    template:
      metadata:
        labels:
          app: kafka1
      spec:
        hostname: kafka1-service
        dnsPolicy: ClusterFirst
        containers:
        - name: ykskafkatest-n1
          image: wurstmeister/kafka:2.11-0.10.2.2
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9092
  #        - containerPort: 1099
          env:
            # broker ID,必须要有,各节点不能一致
          - name: KAFKA_BROKER_ID
            value: "1"
            # 必须要有,zk集群
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper1-service:2181,zookeeper2-service:2181,zookeeper3-service:2181
            # 必须要有,kafka工作端口
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
            # 可选
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: kafka1-service
            # 可选 
          - name: KAFKA_HEAP_OPTS
            value: "-Xmx4G -Xms4G" 
            # JMX相关，可选
  #        - name: KAFKA_JMX_OPTS
  #          value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099"
            # JMX相关，可选
  #        - name: JMX_PORT
  #          value: "1099"
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: kafka2-deployment
    namespace: default
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: kafka2
    template:
      metadata:
        labels:
          app: kafka2
      spec:
        hostname: kafka2-service
        dnsPolicy: ClusterFirst
        containers:
        - name: ykskafkatest-n1
          image: wurstmeister/kafka:2.11-0.10.2.2
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9092
  #        - containerPort: 1099
          env:
            # broker ID,必须要有,各节点不能一致
          - name: KAFKA_BROKER_ID
            value: "2"
            # 必须要有,zk集群
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper1-service:2181,zookeeper2-service:2181,zookeeper3-service:2181
            # 必须要有,kafka工作端口
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
            # 可选
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: kafka2-service
            # 可选 
          - name: KAFKA_HEAP_OPTS
            value: "-Xmx4G -Xms4G" 
            # JMX相关，可选
  #        - name: KAFKA_JMX_OPTS
  #          value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099"
            # JMX相关，可选
  #        - name: JMX_PORT
  #          value: "1099"
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: kafka3-deployment
    namespace: default
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: kafka3
    template:
      metadata:
        labels:
          app: kafka3
      spec:
        hostname: kafka3-service
        dnsPolicy: ClusterFirst
        containers:
        - name: ykskafkatest-n1
          image: wurstmeister/kafka:2.11-0.10.2.2
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9092
  #        - containerPort: 1099
          env:
            # broker ID,必须要有,各节点不能一致
          - name: KAFKA_BROKER_ID
            value: "3"
            # 必须要有,zk集群
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper1-service:2181,zookeeper2-service:2181,zookeeper3-service:2181
            # 必须要有,kafka工作端口
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
            # 可选
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: kafka3-service
            # 可选 
          - name: KAFKA_HEAP_OPTS
            value: "-Xmx4G -Xms4G" 
            # JMX相关，可选
  #        - name: KAFKA_JMX_OPTS
  #          value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099"
            # JMX相关，可选
  #        - name: JMX_PORT
  #          value: "1099"

  