apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: rabbitmq
message: RabbitMQ
metadata:
  annotations:
    description: RabbitMQ
    tags: quickstart,rabbitmq
  name: rabbitmq
  namespace: openshift
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: rabbitmq
    name: rabbitmq
  spec:
    replicas: 1
    selector:
      app: rabbitmq
      deploymentconfig: rabbitmq
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/container.rabbitmq.image.entrypoint: '["/docker-entrypoint.sh","rabbitmq-server"]'
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: rabbitmq
          deploymentconfig: rabbitmq
      spec:
        containers:
        - image: docker.io/rabbitmq:latest
          imagePullPolicy: IfNotPresent
          name: rabbitmq
          ports:
          - containerPort: 5672
            protocol: TCP
          - containerPort: 15671
            protocol: TCP
          - containerPort: 15672
            protocol: TCP
          - containerPort: 25672
            protocol: TCP
          - containerPort: 4369
            protocol: TCP
          - containerPort: 5671
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/rabbitmq
            name: rabbitmq-volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: rabbitmq-volume-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - rabbitmq
        from:
          kind: ImageStreamTag
          name: rabbitmq:3.6.0-management
          namespace: openshift
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: rabbitmq
    name: rabbitmq
  spec:
    ports:
    - name: 4369-tcp
      port: 4369
      protocol: TCP
      targetPort: 4369
    - name: 5671-tcp
      port: 5671
      protocol: TCP
      targetPort: 5671
    - name: 5672-tcp
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: 15671-tcp
      port: 15671
      protocol: TCP
      targetPort: 15671
    - name: 15672-tcp
      port: 15672
      protocol: TCP
      targetPort: 15672
    - name: 25672-tcp
      port: 25672
      protocol: TCP
      targetPort: 25672
    selector:
      app: rabbitmq
      deploymentconfig: rabbitmq
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: rabbitmq
    name: rabbitmq
  spec:
    port:
      targetPort: 15672
    to:
      kind: Service
      name: rabbitmq
      weight: 100
    wildcardPolicy: None
